import './globals.scss';
import localFont from 'next/font/local';

const helveticaNueu = localFont({
  variable: '--font-helvetica-nueu',
  src: [
    {
      path: '../public/fonts/HelveticaNeueLTStd-Lt.otf',
      weight: '300',
      style: 'light',
    },
    {
      path: '../public/fonts/HelveticaNeueLTStd-Md.otf',
      weight: '500',
      style: 'medium',
    },
    {
      path: '../public/fonts/HelveticaNeueLTStd-Bd.otf',
      weight: '700',
      style: 'bold',
    },
  ],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${helveticaNueu.variable} font-sans h-full`}>{children}</body>
    </html>
  )
}
